I've added the tutorials page.
SciSpark/scispark-website pull request #10
Opened 2016-09-08 16:05 UTC by wmburke

I also separated out the header and footer files so that they only have to be updated in one location and not on every single page.

2016-09-14 23:31 UTC, kwhitehall commented on tutorials.html
> +          <li>P. C. Loikith, J. Kim, H. Lee, B. Linter, C. Mattmann, J. J. D. Neelin, D. E. Waliser, L. Mearns, S. McGinnis. Evaluation of Surface Temperature Probability Distribution Functions in th
Please consider the consistency of the reference style within the doc.

2016-09-14 23:42 UTC, kwhitehall commented on tutorials.html
> +          <li>Whitehall, Kim, et al. "Exploring a graph theory based algorithm for automated identification and characterization of large mesoscale convective systems in satellite datasets." Earth Sc
Please check reference style. Also it is Grab 'Em, Graph 'Em and Tag 'Em.

2016-09-14 23:43 UTC, kwhitehall commented on tutorials.html
> +        The sciTensor datatype is a self-documented array that keeps a list of arrays for a variable arrays and maintains associated metadata in a hashmap. The sciTensor is read into the sRDD and the
Typo. SciTnesor should be SciTensor

2016-09-14 23:46 UTC, kwhitehall commented on tutorials.html
> +          <li>Apache Zeppelin, SciSpark, sciRDD</li>
sciRDD? Or sRDD?

2016-09-14 23:48 UTC, kwhitehall commented on tutorials.html
> +        <h2> Presentations (PDFs) </h2>
Consider refraining from using PDFs here to mean the Adobe Document type because the same acronym is used within for our use case

2016-09-14 23:48 UTC, kwhitehall commented on tutorials.html
> +          <li>sciRDD transformation and actions</li>
sRDD transformations and actions

2016-09-14 23:50 UTC, kwhitehall commented on tutorials.html
> +          <li>Extend native Spark on JVM: handle earth science geolocation arrays; netCDF/OpenDAP data ingest; array operation like numpy; two complex use case: MCS and PDF clustering of atmospheric
expound MCS and PDF as first time used here.

2016-09-14 23:53 UTC, kwhitehall requested changes
Hi @wmburke, trying out this new GH interface...let's see what this prepare a review summary does:-)
So I left some inline comments re typos,etc. in the new html (tutorials.html). Also, I notice that when I view the files locally, I don't see the header or footer on the pages. Can you please check on this?

2016-09-15 14:32 UTC, wmburke commented on tutorials.html
> +        <h2> Presentations (PDFs) </h2>
I'm not sure how else to refer to these. Adobe PDFs? Portable Document Formatted presentations? Do you have any suggestions?

2016-09-15 14:36 UTC, wmburke commented on tutorials.html
> +        <h2> Presentations (PDFs) </h2>
what if I just specify PDF files? That should distinguish is sufficiently from PDF clustering, right?

2016-09-15 14:38 UTC, wmburke commented on tutorials.html
> +          <li>Extend native Spark on JVM: handle earth science geolocation arrays; netCDF/OpenDAP data ingest; array operation like numpy; two complex use case: MCS and PDF clustering of atmospheric
Done

2016-09-15 14:39 UTC, wmburke commented on tutorials.html
> +          <li>sciRDD transformation and actions</li>
sciRDD changed to sRDD in the entire document

2016-09-15 14:43 UTC, wmburke commented on tutorials.html
> +          <li>Whitehall, Kim, et al. "Exploring a graph theory based algorithm for automated identification and characterization of large mesoscale convective systems in satellite datasets." Earth Sc
I just copied this text directly from the ESIP events. If you want a different reference style, please tell me what you prefer.

As far as Grab 'Em, Graph 'Em, and Tag 'Em: you have "Grab 'em, Tag 'em, Graph 'em (GTG) algorithm" on your github repo page, so please specify which I should use on the tutorials page to be consistent: https://github.com/kwhitehall/grab-tag-graph

Thanks.

2016-09-15 14:44 UTC, wmburke commented on tutorials.html
> +        The sciTensor datatype is a self-documented array that keeps a list of arrays for a variable arrays and maintains associated metadata in a hashmap. The sciTensor is read into the sRDD and the
fixed

2016-09-15 14:46 UTC, wmburke commented
Thanks, Kim!

When you say you don't see the header and footer files when you look at the page locally, does that mean you don't see it after downloading the new site to your computer? Can you give me a little more detail on this? It works fine on my machine.

2016-09-15 14:48 UTC, wmburke commented
Is jQuery working on your local install? That would be the easy explanation.

2016-09-15 17:09 UTC, kwhitehall commented on tutorials.html
> +        <h2> Presentations (PDFs) </h2>
Ack'ed Wayne. 
Maybe something like 
"The training materials include our presentations, a docker file so you can install and work on SciSpark, and a collection of Notebooks for SciSpark with training examples you can follow and work through.

PRESENTATIONS 
.."
There is rubric to indicate that Adobe reader is needed. So you could refrain from the using the acronym.

2016-09-15 17:12 UTC, kwhitehall commented on tutorials.html
> +          <li>Whitehall, Kim, et al. "Exploring a graph theory based algorithm for automated identification and characterization of large mesoscale convective systems in satellite datasets." Earth Sc
Thank @wmburke. "Grab 'em, Tag 'em, Graph 'em (GTG) algorithm" is the correct terminology. Essentially the _'em_ is short for them... so it just really matters where the apostrophe is.

2016-09-15 17:13 UTC, kwhitehall commented on tutorials.html
> +          <li>P. C. Loikith, J. Kim, H. Lee, B. Linter, C. Mattmann, J. J. D. Neelin, D. E. Waliser, L. Mearns, S. McGinnis. Evaluation of Surface Temperature Probability Distribution Functions in th
Hey @wmburke, I don't think this one was addressed.

2016-09-15 17:32 UTC, kwhitehall commented
JQuery is working on my install, and according to the code, the jquery used comes from bower which is a requirement, so that's consistent between us. I still can't see the header and footer though. Did you edit the .css file as well?

2016-09-15 18:34 UTC, wmburke commented on tutorials.html
> +          <li>Apache Zeppelin, SciSpark, sciRDD</li>
changed

2016-09-15 18:35 UTC, wmburke commented on tutorials.html
> +          <li>Whitehall, Kim, et al. "Exploring a graph theory based algorithm for automated identification and characterization of large mesoscale convective systems in satellite datasets." Earth Sc
Oh I see - ok, I got that one done too.

2016-09-15 18:36 UTC, wmburke commented on tutorials.html
> +          <li>P. C. Loikith, J. Kim, H. Lee, B. Linter, C. Mattmann, J. J. D. Neelin, D. E. Waliser, L. Mearns, S. McGinnis. Evaluation of Surface Temperature Probability Distribution Functions in th
Weird - I know I commented on it. Anyway...

I just copied this text wholesale from the ESIP descriptions. Please tell me how you want the references to appear and I'll just do them like that. I have no opinion on this.

2016-09-15 18:37 UTC, wmburke commented on tutorials.html
> +        <h2> Presentations (PDFs) </h2>
Ok - PDF removed from everywhere except where it refers to PDF clustering.

2016-09-15 18:45 UTC, wmburke commented
Nope - no changes to style.css.

There is a function in the header that should load the header and footer:
29        <script>
30        $(function(){
31          $("#header").load("header.html");
32          $("#footer").load("footer.html");
33        });
34        </script>

I can't recreate the problem on my computer. Let me know if you want to talk this through. I'm free after 1pm pt.

2016-09-15 20:43 UTC, kwhitehall commented on tutorials.html
> +          <li>P. C. Loikith, J. Kim, H. Lee, B. Linter, C. Mattmann, J. J. D. Neelin, D. E. Waliser, L. Mearns, S. McGinnis. Evaluation of Surface Temperature Probability Distribution Functions in th
Ok @wmburke.  Personally, I prefer the succinctness of MLA format, esp since links can be provided to the papers. 

Loikith, Paul C., et al. "Surface Temperature Probability Distributions in the NARCCAP Hindcast Experiment: Evaluation Methodology, Metrics, and Results." Journal of Climate 28.3 (2015): 978-997.

Lee, Seungwon, et al. "Climate model diagnostic analyzer." Big Data (Big Data), 2015 IEEE International Conference on. IEEE, 2015.

Whitehall, Kim, et al. "Exploring a graph theory based algorithm for automated identification and characterization of large mesoscale convective systems in satellite datasets." Earth Science Informatics 8.3 (2015): 663-675.

2016-09-15 20:44 UTC, kwhitehall commented
Thanks @wmburke, I'll take you up on the walk through...

2016-09-15 21:02 UTC, wmburke commented on tutorials.html
> +          <li>P. C. Loikith, J. Kim, H. Lee, B. Linter, C. Mattmann, J. J. D. Neelin, D. E. Waliser, L. Mearns, S. McGinnis. Evaluation of Surface Temperature Probability Distribution Functions in th
done

2016-09-15 21:27 UTC, kwhitehall commented
Hey @wmburke, which browser and version are you using? Also bower and jquery?

2016-09-15 21:46 UTC, kwhitehall commented
W00t! Thanks for the call @wmburke! This LGTM!

2016-09-15 21:46 UTC, kwhitehall commented
@chrismattmann can you please merge this one.

2016-09-15 22:00 UTC, merged